# Generated by Django 6.0.3 on 2026-03-30 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=587)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('_password', models.TextField(blank=True, db_column='password', default='')),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('from_email', models.EmailField(max_length=254)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP Configuration',
                'verbose_name_plural': 'SMTP Configurations',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('DOWN', 'Down'), ('RECOVERY', 'Recovery'), ('RETRY_FAILURE', 'Retry Failure')], max_length=20)),
                ('recipients', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='monitoring.service')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=False)),
                ('notify_on_down', models.BooleanField(default=True)),
                ('notify_on_recovery', models.BooleanField(default=True)),
                ('notify_on_retry_failure', models.BooleanField(default=False)),
                ('cooldown_seconds', models.IntegerField(default=300)),
                ('recipient_emails', models.JSONField(blank=True, default=list)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_policy', to='monitoring.service')),
            ],
            options={
                'verbose_name_plural': 'notification policies',
            },
        ),
    ]
