# Generated by Django 6.0.3 on 2026-03-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationpolicy',
            options={'ordering': ['service__name'], 'verbose_name_plural': 'notification policies'},
        ),
        migrations.AlterModelOptions(
            name='smtpconfig',
            options={'ordering': ['-created_at'], 'verbose_name': 'SMTP Configuration', 'verbose_name_plural': 'SMTP Configurations'},
        ),
    ]
