# Generated by Django 6.0.3 on 2026-03-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name_plural': 'services'},
        ),
    ]
