# Generated by Django 6.0.3 on 2026-03-30 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['url'],
            },
        ),
        migrations.AddField(
            model_name='checkresult',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('TIMEOUT', 'Timeout'), ('DNS_FAILURE', 'DNS Failure'), ('CONNECTION_REFUSED', 'Connection Refused'), ('HTTP_ERROR', 'HTTP Error'), ('VALIDATION_MISMATCH', 'Validation Mismatch'), ('UNKNOWN', 'Unknown')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='network_status',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='response_snippet',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='auto_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='user_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='check_type',
            field=models.CharField(choices=[('API', 'API (structured response)'), ('CONTENT', 'Content (string matching)')], default='API', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='RetryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('max_retries', models.IntegerField(default=3)),
                ('retry_interval_seconds', models.IntegerField(default=10)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retry_policy', to='monitoring.service')),
            ],
            options={
                'verbose_name_plural': 'retry policies',
                'ordering': ['service__name'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CONTAINS', 'Contains'), ('NOT_CONTAINS', 'Not Contains'), ('STATUS_CODE', 'Status Code')], max_length=20)),
                ('value', models.CharField(max_length=500)),
                ('expected', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='monitoring.service')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
