# Generated by Django 6.0.3 on 2026-03-30 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_sync_service_periodic_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='log_retention_limit',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
