# Generated by Django 6.0.3 on 2026-03-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_service_log_retention_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkresult',
            name='full_response_body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
