# Generated by Django 6.0.3 on 2026-03-30 11:59

from django.db import migrations, models


def backfill_service_check_counts(apps, schema_editor):
    Service = apps.get_model('monitoring', 'Service')
    CheckResult = apps.get_model('monitoring', 'CheckResult')

    for service in Service.objects.all():
        checks = CheckResult.objects.filter(service_id=service.pk)
        service.total_check_count = checks.count()
        service.successful_check_count = checks.filter(
            is_successful=True,
        ).count()
        service.failed_check_count = checks.filter(
            is_successful=False,
        ).count()
        service.save(update_fields=[
            'total_check_count',
            'successful_check_count',
            'failed_check_count',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_checkresult_full_response_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='failed_check_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='successful_check_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='total_check_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(
            backfill_service_check_counts,
            migrations.RunPython.noop,
        ),
    ]
