# Generated by Django 6.0.3 on 2026-03-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_service_failed_check_count_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='checkresult',
            index=models.Index(fields=['service', '-checked_at'], name='idx_check_svc_time'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['service', 'is_resolved', '-started_at'], name='idx_inc_svc_resolved'),
        ),
    ]
